sudo pip3 install matplotlib
sudo pip3 install nolearn
sudo pip3 install caffe
sudo pip3 install torch
sudo pip3 install MXNet
sudo pip3 install Lasagne
sudo pip3 install keras
sudo pip3 install Pillow
sudo pip3 install tensorflow
sudo pip3 install scikit-learn
sudo pip3 install Pandas
sudo pip3 install Pylearn2
sudo pip3 install NuPIC
sudo pip3 install Nilearn
sudo pip3 install PyBrain
sudo pip3 install Pattern
sudo pip3 install Fuel
sudo pip3 install Bob
sudo pip3 install Skdata
sudo pip3 install MILK
sudo pip3 install IEPY
sudo pip3 install Quepy
sudo pip3 install Hebel
sudo pip3 install mlxtend
sudo pip3 install nolearn
sudo pip3 install Ramp
sudo pip3 install featureforge
sudo pip3 install REP
